# Generated by Django 4.2.8 on 2025-04-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojoregistrationlink',
            options={},
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='website',
        ),
        migrations.RemoveField(
            model_name='dojoregistrationlink',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='dojoregistrationlink',
            name='uses_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='portal.dojoregistrationlink'),
        ),
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dojoregistrationlink',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='address',
            field=models.TextField(default='Address not specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dojo',
            name='email',
            field=models.EmailField(default='email not specified', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dojo',
            name='phone',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dojoregistrationlink',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dojoregistrationlink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dojoregistrationlink',
            name='max_uses',
            field=models.IntegerField(default=0, help_text='Maximum number of registrations (0 = unlimited)'),
        ),
    ]
