# Generated by Django 4.2.8 on 2025-02-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customuser_address_customuser_city_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='belt',
            field=models.CharField(choices=[('none', 'None'), ('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('brown', 'Brown'), ('black', 'Black')], default='none', max_length=10),
        ),
    ]
