# Generated by Django 4.2.8 on 2025-04-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_dojoregistrationlink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='description',
        ),
        migrations.AddField(
            model_name='dojo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
