# Generated by Django 4.2.8 on 2025-08-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_dojo_description_dojo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dojo_logos/'),
        ),
        migrations.AddField(
            model_name='dojo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
