# Generated by Django 4.2.8 on 2025-02-24 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_eventfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfeedback',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventfeedback',
            name='is_read',
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
