# Generated by Django 4.2.8 on 2025-02-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_rename_comment_eventfeedback_content_and_more'),
    ]

    operations = [
    ]
