# Generated by Django 4.2.8 on 2025-03-27 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_feedbacktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt', models.CharField(choices=[('none', 'None'), ('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('brown', 'Brown'), ('black', 'Black')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('all_belts', models.BooleanField(default=False, help_text='Apply this criteria to all belt levels')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Belt Criteria',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentCriteriaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_criteria', to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.beltcriteria')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'criteria')},
            },
        ),
    ]
