# Generated by Django 4.2.8 on 2025-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_beltcriteria_studentcriteriaprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='category',
            field=models.CharField(choices=[('strengths', 'Strengths'), ('growth', 'Areas for Growth'), ('next_steps', 'Next Steps')], default='strengths', max_length=20),
        ),
    ]
