# Generated by Django 4.2.8 on 2025-04-05 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_feedbacktemplate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting'), ('tournament', 'Tournament'), ('birthday', 'Birthday'), ('other', 'Other')], default='other', max_length=20)),
                ('background_color', models.CharField(default='#3c8dbc', max_length=20)),
                ('repeats', models.BooleanField(default=False)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
