# Generated by Django 4.2.8 on 2025-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('class', 'Class'), ('event', 'Event'), ('holiday', 'Holiday'), ('birthday', 'Birthday'), ('tournament', 'Tournament'), ('testing', 'Belt Testing'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
