# Generated by Django 4.2.8 on 2025-04-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_rename_event_type_calendarevent_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_types',
        ),
    ]
