# Generated by Django 4.2.8 on 2025-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_remove_calendarevent_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_birthday',
            field=models.BooleanField(default=False),
        ),
    ]
